on:
  pull_request:
    branches:
      ci-add-examples-test-211

jobs:
  examples-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] #[macos-latest, ubuntu-latest]
        python-version: [3.7,]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[match-py-ver] --no-cache-dir
      - name: Test with pytest
        run: |
          # make sure docker exist
          docker ps
          jina check
          docker build  -f Dockerfiles/pip.Dockerfile -t jinaai/jina:test-pip .
          export JINA_LOG_VERBOSITY="ERROR"
          pip install .[test]
          git clone https://github.com/jina-ai/examples.git --branch test-examples-cicd
          pytest --force-flaky --min-passes 1 -n 1 --timeout=120 -v examples/southpark-search
        timeout-minutes: 60
        env:
          JINAHUB_USERNAME: ${{ secrets.JINAHUB_USERNAME }}
          JINAHUB_PASSWORD: ${{ secrets.JINAHUB_PASSWORD }}